Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -10,23 +10,61 @@ on:
     branches: [ main ]
 
 jobs:
-  setup:
+   setup: 
     runs-on: self-hosted
     steps:
-      - name: Check out code
-        uses: actions/checkout@v4
-      - name: Install Git
-        run: sudo apt-get install -y git
-      - name: Install Docker
+      - name: Check for Git
         run: |
-          sudo apt-get update
-          sudo apt-get install -y docker.io
-      - name: Install Docker Compose
+          if ! command -v git &> /dev/null
+          then
+              echo "Git not found, installing..." 
+              sudo apt-get update
+              sudo apt-get install -y git
+          else
+              echo "Git is already installed."
+          fi
+
+      - name: Check for Docker
         run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-      - name: Install Maven
-        run: sudo apt-get install -y maven
+          if ! command -v docker &> /dev/null
+          then
+              echo "Docker not found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y \
+                apt-transport-https \
+                ca-certificates \
+                curl \
+                gnupg-agent \
+                software-properties-common && \
+                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
+                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
+                sudo apt-get update && \
+                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+          else
+              echo "Docker is already installed."
+          fi
+
+      - name: Check for Docker Compose
+        run: |
+          if ! command -v docker-compose &> /dev/null
+          then
+              echo "Docker Compose not found, installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+          else
+              echo "Docker Compose is already installed."
+          fi
+
+      - name: Check for Maven
+        run: |
+          if ! command -v mvn &> /dev/null
+          then
+              echo "Maven not found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y maven
+          else
+              echo "Maven is already installed."
+          fi
 
   build:
     runs-on: self-hosted
